---
name: Yaml-Checker
description: 'This GitHub action automatically checks your code for errors,
              in YAML files when a pull request comes or the code is pushed'
author: 'leon-th'
branding:
  icon: 'check-circle'
  color: 'blue'
on:
  - "push"
  - "pull_request"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install yamllint
        run: |
          sudo apt-get install yamllint
      - name: Test yamllint
        run: |
          yamllint .
