name: Yaml-Checker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install yamllint
      run: |
        sudo apt-get install yamllint
    - name: Test yamllint
      run: |
        yamllint .
